exports.seed = function (knex, Promise) {
  return knex('nouns').insert([
{ id: 1, user_id:1,content:'Alex Jones'},
{ id: 2, user_id:1,content:'Hillary Clinton'},
{ id: 3, user_id:1,content:'Bill Clinton'},
{ id: 4, user_id:1,content:'The Illuminati'},
{ id: 5, user_id:1,content:'The federal government'},
{ id: 6, user_id:1,content:'Conor Mcgregor'},
{ id: 7, user_id:1,content:'Jeff Bezos'},
{ id: 8, user_id:1,content:'Donald Trump'},
{ id: 9, user_id:1,content:'The Magnificent Twelve'},
{ id: 10, user_id:1,content:'The FBI'},
{ id: 11, user_id:1,content:'Michael Jackson'},
{ id: 12, user_id:1,content:'R Kelly'},
{ id: 13, user_id:1,content:'Jay Inslee'},
{ id: 14, user_id:1,content:'Vincent D\'onofrio'},
{ id: 15, user_id:1,content:'Alexander Graham Bell'},
{ id: 16, user_id:1,content:'Our founding father'},
{ id: 17, user_id:1,content:'Captain James Tiberius Kirk'},
{ id: 18, user_id:1,content:'Justin Timberlake'},
{ id: 19, user_id:1,content:'Lindsey Lohan'},
{ id: 20, user_id:1,content:'Britney Spears'},
{ id: 21, user_id:1,content:'The Dean of UCLA'},
{ id: 22, user_id:1,content:'Jeffrey Tambor'},
{ id: 23, user_id:1,content:'DMX'},
{ id: 24, user_id:1,content:'Wakka Flakka Flame'},
{ id: 25, user_id:1,content:'Russel Simmons'},
{ id: 26, user_id:1,content:'James Franco'},
{ id: 27, user_id:1,content:'Steven Tyler'},
{ id: 28, user_id:1,content:'Joe Perry'},
{ id: 29, user_id:1,content:'Steve Perry'},
{ id: 30, user_id:1,content:'Sarah MacLachlan'},
{ id: 31, user_id:1,content:'Aziz Ansari'},
{ id: 32, user_id:1,content:'Jeffrey Epstein'},
{ id: 33, user_id:1,content:'Mark Cuban'},
{ id: 34, user_id:1,content:'Damond Dash'},
{ id: 35, user_id:1,content:'Barbara Corcoran'},
{ id: 36, user_id:1,content:'Jared Fogle'},
{ id: 37, user_id:1,content:'Theo Von'},
{ id: 38, user_id:1,content:'Brendan Schaub'},
{ id: 39, user_id:1,content:'Carlos Mencia'},
{ id: 40, user_id:1,content:'Jesse Jones'},
{ id: 41, user_id:1,content:'Steve Pool'},
{ id: 42, user_id:1,content:'Fedor Emelianienko'},
{ id: 43, user_id:1,content:'Dante Alighieri'},
{ id: 44, user_id:1,content:'John Grisham'},
{ id: 45, user_id:1,content:'Woody Harrellson'},
{ id: 46, user_id:1,content:'Mathew McConaughey'},
{ id: 47, user_id:1,content:'Danny Glover'},
{ id: 48, user_id:1,content:'Mel Gibson'},
{ id: 49, user_id:1,content:'Frank Sinatra'},
{ id: 50, user_id:1,content:'George Lucas'},
{ id: 51, user_id:1,content:'Childish Gambino'},
{ id: 52, user_id:1,content:'Tupac Shakur'},
{ id: 53, user_id:1,content:'The Notorious B.I.G.'},
{ id: 54, user_id:1,content:'Christina Aguilera'},
{ id: 55, user_id:1,content:'Carson Daily'},
{ id: 56, user_id:1,content:'Dax Shephard'},
{ id: 57, user_id:1,content:'Kirsten Bell'},
{ id: 58, user_id:1,content:'Malcom Gladwell'},
{ id: 59, user_id:1,content:'Ghandi'},
{ id: 60, user_id:1,content:'Ron Swanson'},
{ id: 61, user_id:1,content:'Steve Carrell'},
{ id: 62, user_id:1,content:'Jon Krasinski'},
{ id: 63, user_id:1,content:'Rainn Wilson'},
{ id: 64, user_id:1,content:'John Carpenter'},
{ id: 65, user_id:1,content:'Oprah Winfrey'},
{ id: 66, user_id:1,content:'Tom Brady'},
{ id: 67, user_id:1,content:'Russell Wilson'},
{ id: 68, user_id:1,content:'Aaron Rodgers'},
{ id: 69, user_id:1,content:'Ben Roethlisberger'},
{ id: 70, user_id:1,content:'Brad Pitt'},
{ id: 71, user_id:1,content:'Jennifer Aniston'},
{ id: 72, user_id:1,content:'Mathew Lillard'},
{ id: 73, user_id:1,content:'Courtney Cox'},
{ id: 74, user_id:1,content:'Matt LeBlanc'},
{ id: 75, user_id:1,content:'Matthew Perry'},
{ id: 76, user_id:1,content:'David Schwimmer'},
{ id: 77, user_id:1,content:'Jerry Seinfeld'},
{ id: 78, user_id:1,content:'Jason Alexander'},
{ id: 79, user_id:1,content:'Michael Richards'},
{ id: 80, user_id:1,content:'Adolf Hitler\'s nephew'},
{ id: 81, user_id:1,content:'James Brown'},
{ id: 82, user_id:1,content:'Gwen Stefani'},
{ id: 83, user_id:1,content:'Eddie Vedder'},
{ id: 84, user_id:1,content:'James Hetfield'},
{ id: 85, user_id:1,content:'Metallica'},
{ id: 86, user_id:1,content:'My Chemical Romance'},
{ id: 87, user_id:1,content:'George Lopez'},
{ id: 88, user_id:1,content:'Lars Von Trier'},
{ id: 89, user_id:1,content:'Elvis Presley'},
{ id: 90, user_id:1,content:'Andy Dick'},
{ id: 91, user_id:1,content:'Elon Musk'},
{ id: 92, user_id:1,content:'Bill Gates'},
{ id: 93, user_id:1,content:'Matt Groening'},
{ id: 94, user_id:1,content:'Joseph Smith'},
{ id: 95, user_id:1,content:'The coastal elite'},
{ id: 96, user_id:1,content:'Pennsylvania democrats'},
{ id: 97, user_id:1,content:'Senator Patty Murray'},
{ id: 98, user_id:1,content:'Howard Stern'},
{ id: 99, user_id:1,content:'Rip Torn'},
{ id: 100, user_id:1,content:'Casey Kasem'},
{ id: 101, user_id:1,content:'Engelbert Humperdink'},
{ id: 102, user_id:1,content:'Steve Jobs'},
{ id: 103, user_id:1,content:'Mark Zuckerberg'},
{ id: 104, user_id:1,content:'Howard Schulz'},
{ id: 105, user_id:1,content:'The Walton Family'},
{ id: 106, user_id:1,content:'The executive board of Babies R\' Us'},
{ id: 107, user_id:1,content:'Wolf Blitzer'},
{ id: 108, user_id:1,content:'Stone Phillips'},
{ id: 109, user_id:1,content:'Dan Rather'},
{ id: 110, user_id:1,content:'Kim Kardashian'},
{ id: 111, user_id:1,content:'Charles Barkley'},
{ id: 112, user_id:1,content:'Sandra Bullock'},
{ id: 113, user_id:1,content:'Jason Bateman'},
{ id: 114, user_id:1,content:'David Letterman'},
{ id: 115, user_id:1,content:'Conan O\' Brien'},
{ id: 116, user_id:1,content:'Jay Leno'},
{ id: 117, user_id:1,content:'Jimmy Fallon'},
{ id: 118, user_id:1,content:'James Corden'},
{ id: 119, user_id:1,content:'Anna Paquin'},
{ id: 120, user_id:1,content:'George Romero'},
{ id: 121, user_id:2,content:'The cast of The Fast and the Furious'},
{ id: 122, user_id:2,content:'Paul Walker'},
{ id: 123, user_id:2,content:'Steve Wozniak'},
{ id: 124, user_id:3,content:'Jim Parsons'},
{ id: 125, user_id:3,content:'Alex Rodriguez'},
{ id: 126, user_id:3,content:'Barry Bonds'},
{ id: 127, user_id:4,content:'George W Bush'},
{ id: 128, user_id:4,content:'Thomas Jefferson'},
{ id: 129, user_id:4,content:'Kelly Clarkson'},
{ id: 130, user_id:5,content:'Cormac McCarthy'},
{ id: 131, user_id:5,content:'Henry David Thoreau'},
{ id: 132, user_id:5,content:'Michael Crichton'},
{ id: 133, user_id:6,content:'Rupaul'},
{ id: 134, user_id:6,content:'The cast of the musical Cats'},
{ id: 135, user_id:6,content:'Bill W'},
{ id: 136, user_id:7,content:'Edward Snowden'},
{ id: 137, user_id:7,content:'Ned Flanders'}
  ])
    .then(() => {
      return knex.raw("SELECT setval('nouns_id_seq', (SELECT MAX(id) FROM nouns));")
    })
}
