exports.seed = function (knex, Promise) {
  return knex('verbs').insert([
{ id: 1, user_id:1,content:'put flouride in our drinking water in order to control out minds'},
{ id: 2, user_id:1,content:'was responsible for  9/11'},
{ id: 3, user_id:1,content: 'is the orchestrator of pizzagate'},
{ id: 4, user_id:1,content:'embezzles from the Boeing pension fund'},
{ id: 5, user_id:1,content: 'can control the weather'},
{ id: 6, user_id:1,content:'has the key to entering the matrix'},
{ id: 7, user_id:1,content: 'is actually the tooth fairy'},
{ id: 8, user_id:1,content:'invented the phrase "YOLO"'},
{ id: 9, user_id:1,content:'invented the internet'},
{ id: 10, user_id:1,content:'sells organs on the black market'},
{ id: 11, user_id:1,content:'is the real Dread Pirate Roberts'},
{ id: 12, user_id:1,content:'never learned to read'},
{ id: 13, user_id:1,content:'knows that Nicholas Cage actually did steal the declaration of independence'},
{ id: 14, user_id:1,content:'successfully cloned a congressman'},
{ id: 15, user_id:1,content: 'is actually over 600 years old'},
{ id: 16, user_id:1,content:'plays poker with the devil'},
{ id: 17, user_id:1,content:'Captain James Tiberius Kirk'},
{ id: 18, user_id:1,content:'has danced with the devil in the pale moonlight'},
{ id: 19, user_id:1,content:'ghost wrote all of Shakespeare\'s plays'},
{ id: 20, user_id:1,content:'is actually a clone'},
{ id: 21, user_id:1,content:'The Dean of UCLA'},
{ id: 22, user_id:1,content:'has kept a tight lid on hydro-fusion'},
{ id: 23, user_id:1,content:'funds dark-web red rooms'},
{ id: 24, user_id:1,content:'is actually one of a set of triplets'},
{ id: 25, user_id:1,content:'is actually two dwarves in a trenchcoat'},
{ id: 26, user_id:1,content:'orchestrated the invasion of Iraq'},
{ id: 27, user_id:1,content:'planned the Bay of Pigs invasion'},
{ id: 28, user_id:1,content:'funds online Red Rooms'},
{ id: 29, user_id:1,content:'released crack-cocaine to the public'},
{ id: 30, user_id:1,content:'killed JFK'},
{ id: 31, user_id:1,content:'hangs out with aliens'},
{ id: 32, user_id:1,content:'knows that Men In Black is a true story'},
{ id: 33, user_id:1,content:'lied on the mortgage application'},
{ id: 34, user_id:1,content:'was the true author of War and Peace'},
{ id: 35, user_id:1,content:'invented the cobb salad'},
{ id: 36, user_id:1,content:'has Benjamin Button syndrome'},
{ id: 37, user_id:1,content:'records all of your movements'},
{ id: 38, user_id:1,content:'faked the moon landing'},
{ id: 39, user_id:1,content:'perpetuated the lie that the moon is in fact made of cheese'},
{ id: 40, user_id:1,content:'was the entity on the grassy knoll'},
{ id: 41, user_id:1,content:'put Lee Harvey Oswald up to it'},
{ id: 42, user_id:1,content:'knows that James Earl Ray didn\'t kill MLK Jr'},
{ id: 43, user_id:1,content:'operates a car theft ring'},
{ id: 44, user_id:1,content:'ran a bigfoot breeding program'},
{ id: 45, user_id:1,content:'killed and made bigfoot into a rug'},
{ id: 46, user_id:1,content:'embezzled from the ILWU pension fund'},
{ id: 47, user_id:1,content:'performed cattle mutilations and blames the catholic church'},
{ id: 48, user_id:1,content:'printed counterfeit money and used it to bribe government officials'},
{ id: 49, user_id:1,content:'ran a prostituion ring out of a Chuck E Cheese'},
{ id: 50, user_id:1,content:'framed Roger Rabbit'},
{ id: 51, user_id:1,content:'started a cult in Azerbaijan'},
{ id: 52, user_id:1,content:'poisoned the watering hole'},
{ id: 53, user_id:1,content:'uses numbers station to distribute propaganda'},
{ id: 54, user_id:1,content:'stole the cookie from the cookie jar'},
{ id: 55, user_id:1,content:'puts razorblades in halloween candy'},
{ id: 56, user_id:1,content:'kept chupacabras as pets'},
{ id: 57, user_id:1,content:'knows that reptilian shapeshifters are real'},
{ id: 58, user_id:1,content:'is a reptilian shapeshifter'},
{ id: 59, user_id:1,content:'funneled money to neo-nazis'},
{ id: 60, user_id:1,content:'made Trader Joe\'s parking lots small to give the appearance of more business'},
{ id: 61, user_id:1,content:'was the brains behind watergate'},
{ id: 62, user_id:1,content:'got America involved in the Vietnam conflict'},
{ id: 63, user_id:1,content:'used Freeway Ricky Ross to traffic cocaine'},
{ id: 64, user_id:1,content:'is in cahoots with El Chapo'},
{ id: 65, user_id:1,content:'secretly backs the Sinaloa cartel'},
{ id: 66, user_id:1,content:'was in cahoots with Pablo Escobar'},
{ id: 67, user_id:1,content:'was the real Slim Shady'},
{ id: 68, user_id:1,content:'took the lindbergh baby'},
{ id: 69, user_id:1,content:'perpetrated the largest ponzi scheme of all time'},
{ id: 70, user_id:1,content:'used shell companies to launder money'},
{ id: 71, user_id:1,content:'set fires in the Amazon rainforest'},
{ id: 72, user_id:1,content:'stole cable television'},
{ id: 73, user_id:1,content:'sold cable descramblers'},
{ id: 74, user_id:1,content:'tried to pass off Dominican cigars as cubans'},
{ id: 75, user_id:1,content:'violated the Cuban trade embargo'},
{ id: 76, user_id:1,content:'leaked secrets to Vladimir Putin'},
{ id: 77, user_id:1,content:'made that phone call to the Ukraine'},
{ id: 78, user_id:1,content:'was the real Green River Killer'},
{ id: 79, user_id:1,content:'was Ted Bundy\'s accomplice'},
{ id: 80, user_id:1,content:'Adolf Hitler\'s nephew'},
{ id: 81, user_id:1,content:'bugged the White House phone'},
{ id: 82, user_id:1,content:'took a dive in the prize fight'},
{ id: 83, user_id:1,content:'is not real'},
{ id: 84, user_id:1,content:'does not exist'},
{ id: 85, user_id:1,content:'created Isis'},
{ id: 86, user_id:1,content:'is the brains behind election tampering'},
{ id: 87, user_id:1,content:'has hitmen on retainer'},
{ id: 88, user_id:1,content:'started the idea that Australia does not exist'},
{ id: 89, user_id:1,content:'kept the Jersey Devil as a pet'},
{ id: 90, user_id:1,content:'sympathized with the Nazi party'},
{ id: 91, user_id:1,content:'invented rollerblades as a method of oppression'},
{ id: 92, user_id:1,content:'killed small animals for fun'},
{ id: 93, user_id:1,content:'sawed the barrels of their guns to an illegal length'},
{ id: 94, user_id:1,content:'dealt weapons to resistance fighters'},
{ id: 95, user_id:1,content:'started the flat-earth theory'},
{ id: 96, user_id:1,content:'Pennsylvania democrats'},
{ id: 97, user_id:1,content:'stole money from the church collection plate'},
{ id: 98, user_id:1,content:'covered up Nixon\'s indescretions'},
{ id: 99, user_id:1,content:'killed Teresa Halbach'},
{ id: 100, user_id:1,content:'dealt cards from the bottom of the deck'},
{ id: 101, user_id:1,content:'crowdfunds terrorism'},
{ id: 102, user_id:1,content:'sheltered Osama Bin Laden'},
{ id: 103, user_id:1,content:'has been dead for 40 years'},
{ id: 104, user_id:1,content:'wrongfully convicted people to fill for-profit prisons'},
{ id: 105, user_id:1,content:'printed the brand name on candy to save chocolate'},
{ id: 106, user_id:1,content:'was behind MK Ultra'},
{ id: 107, user_id:1,content:'is a pod-person'},
{ id: 108, user_id:1,content:'disposes of bodies with a pig farm'},
{ id: 109, user_id:1,content:'commits murder in the name of Baphomet'},
{ id: 110, user_id:1,content:'worshipped the devil'},
{ id: 111, user_id:1,content:'planned the Waco invasion'},
{ id: 112, user_id:1,content:'shot Greedo first'},
{ id: 113, user_id:1,content:'fired at Han Solo first'},
{ id: 114, user_id:1,content:'ran a poppy plantation'},
{ id: 115, user_id:1,content:'trafficked methamphetamine precursors'},
{ id: 116, user_id:1,content:'falsified court records'},
{ id: 117, user_id:1,content:'smuggled counterfeit goods from China'},
{ id: 118, user_id:1,content:'stole candy from a baby'},
{ id: 119, user_id:1,content:'covered up government assassinations'},
{ id: 120, user_id:1,content:'sold secrets to the communists'},
{ id: 121, user_id:1,content:'lied about vaccines causing autism'},
{ id: 122, user_id:1,content:'cut corners on construction jobs'},
{ id: 123, user_id:1,content:'skipped out on many bar tabs'},
{ id: 124, user_id:1,content:'lied under oath'},
{ id: 125, user_id:1,content:'printed fake $2 bills'},
{ id: 126, user_id:1,content:'tried to stop the march at Selma'},
{ id: 127, user_id:1,content:'has the sketchiest of pasts'},
{ id: 128, user_id:1,content:'embezzled money like the warden from Shawshank Redemption'},
{ id: 129, user_id:1,content:'made sure that OJ\'s glove didn\'t fit'},
{ id: 130, user_id:1,content:'stole copper wire from construction sites'},
{ id: 131, user_id:1,content:'ran a moonshine operation'},
{ id: 132, user_id:1,content:'left a trail of dead bodies'},
{ id: 133, user_id:1,content:'engineered the Corona virus'},
{ id: 134, user_id:1,content:'was the real Walter White'},
{ id: 135, user_id:1,content:'did Putin\'s dirty work'},
{ id: 136, user_id:1,content:'just wanted to watch the world burn'},
{ id: 137, user_id:1,content:'helped the Nazi party steal artwork'}
  ])
    .then(() => {
      return knex.raw("SELECT setval('verbs_id_seq', (SELECT MAX(id) FROM verbs));")
    })
}
