exports.seed = function (knex, Promise) {
  return knex('descriptors').insert([
{id:1,user_id:1,content: 'and there are no regrets about it'},
{id:2,user_id:1,content: 'and yet the people are cool with it'},
{id:3,user_id:1,content: 'which is so uncool'},
{id:4,user_id:1,content: 'and it isn\'t the first time'},
{id:5,user_id:1,content: 'and yet the world still turns'},
{id:6,user_id:1,content: 'and that is how it goes'},
{id:7,user_id:1,content: 'and you are next!'},
{id:8,user_id:1,content: 'and also is a flat-eather'},
{id:9,user_id:1,content: 'and is alive and well in Cuba'},
{id:10,user_id:1,content: 'and has never paid federal income tax'},
{id:11,user_id:1,content:'and tried to frame the pope for it'},
{id:12,user_id:1,content:'and wouldn\'t hesitate to do it again'},
{id:13,user_id:1,content:'and has never given it a second thought'},
{id:14,user_id:1,content:'and you are just going to sit there?!'},
{id:15,user_id:1,content:'and what are you gonna do about it?!'},
{id:16,user_id:1,content:'and it is best to just make peace with that'},
{id:17,user_id:1,content:'and there is little that you can do'},
{id:18,user_id:1,content:'and it might just mean the end of us all'},
{id:19,user_id:1,content:'and this is what makes Jeff Bezos sleep soundly'},
{id:20,user_id:1,content:'and thus all the world is a stage'},
{id:21,user_id:1,content:'and it is the sign of the end of times'},
{id:22,user_id:1,content:'and it may bring on the apocalypse'},
{id:23,user_id:1,content:'and frankly it was about time'},
{id:24,user_id:1,content:'and we never saw this coming'},
{id:25,user_id:1,content:'and so it is time to abandon all hope'},
{id:26,user_id:1,content:'and it is best to just let it go'},
{id:27,user_id:1,content:'and that is tied up in a tidy little package'},
{id:28,user_id:1,content:'and I urge you to intervene'},
{id:29,user_id:1,content:'and you are powerless to intervene'},
{id:30,user_id:1,content:'and knowing is half the battle'},
{id:31,user_id:1,content:'and it is a whole thing'},
{id:32,user_id:1,content:'so whatcha gonna do about it?'},
{id:33,user_id:1,content:'and I will leave you with that information'},
{id:34,user_id:1,content:'so marinate on that for a minute'},
{id:35,user_id:1,content:'and it wasn\'t a solo job'},
{id:36,user_id:1,content:'and they did not act alone'},
{id:37,user_id:1,content:'and they sleep just fine at night'},
{id:38,user_id:1,content:'and it was probably inevitable'},
{id:39,user_id:1,content:'and it was the smallest offense committed'},
{id:40,user_id:1,content:'and that should spook you to the core'},
{id:41,user_id:2,content:'and I wish I didn\'t know the truth'},
{id:42,user_id:2,content:'and you do not know the half of it'},
{id:43,user_id:2,content:'and now your eyes are open'},
{id:44,user_id:2,content:'and history will repeat itself'},
{id:45,user_id:2,content:'and they know that time is a flat circle'},
{id:46,user_id:3,content:'and it was not even considered a big deal'},
{id:47,user_id:3,content:'and it occurred multiple times'},
{id:48,user_id:3,content:'and the truth is still buried'},
{id:49,user_id:3,content:'and the public has no clue'},
{id:50,user_id:3,content:'and I wish I had thought of it first'},
{id:51,user_id:3,content:'and it will happen again'}
  ])
    .then(() => {
      return knex.raw("SELECT setval('descriptors_id_seq', (SELECT MAX(id) FROM descriptors));")
    })
}
